#!/bin/env python3

import os
import subprocess
import argparse

ap = argparse.ArgumentParser()
ap.add_argument('assign', type=str, help="assignment name")
args = vars(ap.parse_args())

subprocess.run(['scp', '-r', ap['assign'], os.environ("utln") + "@homework.cs.tufts.edu:~/cs-15/"])
